language: python
python:
  - "2.7"

sudo: false
cache: pip

install:
    - pip install -r requirements.txt
    - pip install nose codecov flake8 pep8-naming

script:
    - ./linter.sh
    - ./coverage.sh
    - python setup.py install

after_success:
    - codecov
